#!/bin/bash
# s0fractal Ring Builder v1.0
# Usage: λ ring <layer_id> (e.g., 0, 1, 2)

LAYER=$1
if [ -z "$LAYER" ]; then echo "Usage: $0 <layer_number>"; exit 1; fi

# Налаштування
ORG="s0fractal"
RING_NAME="$LAYER"
DIMS=("ts" "rs" "lean" "wasm" "md") # Спектр, який ми шукаємо

echo "🪐 Forging Super-Ring: '$RING_NAME'..."

# 1. Підготовка локальної папки (поза межами Void, щоб не вкладати репо в репо)
WORK_DIR="../$RING_NAME"
if [ -d "$WORK_DIR" ]; then echo "⚠️  Directory $WORK_DIR already exists!"; exit 1; fi

mkdir -p "$WORK_DIR"
cd "$WORK_DIR"
git init -b main

# 2. Вживлення Ядра (Void)
# Кожне кільце має знати закони
mkdir -p meta
git submodule add git@github.com:$ORG/-.git meta/root

# 3. Пошук і Лінковка Нод (Сабмодулі)
echo "🧲 Attracting Nodes..."
FOUND_NODES=0

for DIM in "${DIMS[@]}"; do
    NODE_NAME="$LAYER-$DIM"
    REPO_URL="git@github.com:$ORG/$NODE_NAME.git"
    
    # Перевіряємо через gh api, чи існує такий репо
    if gh repo view "$ORG/$NODE_NAME" >/dev/null 2>&1; then
        echo "   ⊕ Linked: $NODE_NAME -> ./$DIM"
        git submodule add "$REPO_URL" "$DIM"
        ((FOUND_NODES++))
    else
        echo "   . Missing: $NODE_NAME (skipping)"
    fi
done

# 4. Генерація Пояснювального Шару (MD)
# Ми читаємо гліф з метаданих Void (якщо вони є) або ставимо заглушку
echo "📜 Writing Chronicles..."

cat << MD_EOF > README.md
# Σ-Ring: Level $LAYER

> Цей репозиторій є агрегатором понять рівня $LAYER у системі s0fractal.

## Спектральний Склад
Цей концепт реалізовано у таких вимірах:

| Вимір | Статус |
|-------|--------|
MD_EOF

# Дописуємо таблицю на основі того, що знайшли
for DIM in "${DIMS[@]}"; do
    if [ -d "$DIM" ]; then
        echo "| **$DIM** | ✅ Connected |" >> README.md
    else
        echo "| **$DIM** | 🌑 Void |" >> README.md
    fi
done

echo "Generated by ring.sh on $(date)" >> README.md

# 5. Матеріалізація на GitHub
git add .
git commit -m "⊕ Genesis: Ring $LAYER created with $FOUND_NODES nodes"

echo "☁️  Pushing Ring to Sky..."
gh repo create "$ORG/$RING_NAME" --public --source=. --remote=origin --push

echo "✅ Super-Ring '$RING_NAME' is active."
echo "🔗 URL: https://github.com/$ORG/$RING_NAME"
