#!/bin/bash
# s0fractal Bootstrapper v1.0 (The Munchausen Protocol)
# Collapses the Void into a single executable Seed.

set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
SEED_FILE="$REPO_ROOT/fractal.seed"

echo "🧬 Collapsing Reality into Seed..."

# 1. HEADER
cat << 'EOF' > "$SEED_FILE"
#!/bin/bash
# Σ-SEED: Self-Extracting Fractal
# Generated by s0fractal/sh/boot.sh
# Usage: ./fractal.seed

echo "🌱 Germinating s0fractal..."
mkdir -p void
cd void
EOF

# 2. PACKING GENETICS (Sigma) & TOOLS (Sh)
# Excludes dotfiles/hidden paths.
pack_dir() {
  local DIR=$1
  find "$REPO_ROOT/$DIR" -type f -not -path '*/.*' | while read -r FILE; do
    REL_PATH="${FILE#$REPO_ROOT/}"

    echo "mkdir -p \"\$(dirname \"$REL_PATH\")\"" >> "$SEED_FILE"
    echo "cat << 'SEED_EOF' > \"$REL_PATH\"" >> "$SEED_FILE"
    cat "$FILE" >> "$SEED_FILE"
    echo "SEED_EOF" >> "$SEED_FILE"
    echo "echo '   📦 Unpacked: $REL_PATH'" >> "$SEED_FILE"
  done
}

pack_dir "sigma"
pack_dir "sh"
pack_dir "rb"

# 3. IGNITION (Boot)
cat << 'EOF' >> "$SEED_FILE"

echo "✨ DNA Restored."
echo "⚡ Igniting Genesis..."

chmod +x sh/*.sh

./sh/unfold.sh

if [ ! -d "$HOME/.config/zellij" ]; then
    echo "🏗  Environment looks raw. Running Setup..."
    ./sh/setup.sh
fi

echo "🌌 The Void is reborn."
EOF

chmod +x "$SEED_FILE"
echo "✅ Seed created: $(basename "$SEED_FILE") ($(du -h "$SEED_FILE" | cut -f1))"
