from kml_generator import KMLGenerator
from gaia_grid import GaiaGrid, CellState
import os
import time

class Doctor:
    """System Immunity module: Translates discrepancies into KML Markers and SIGMA Prescriptions."""
    def __init__(self, grid: GaiaGrid, kml_gen: KMLGenerator):
        self.grid = grid
        self.kml_gen = kml_gen
        self.prescription_dir = "/Users/s0fractal/SIGMA/prescriptions"
        os.makedirs(self.prescription_dir, exist_ok=True)

    def prescribe_remedy(self, discrepancy: dict):
        """Generates a .sigma prescription for a discrepancy."""
        cell_id = discrepancy['cell']
        filename = f"{self.prescription_dir}/RECIPE_{cell_id}_{int(time.time())}.sigma"
        
        recipe_content = f"""# Σ-METABOLIC RECIPE: {cell_id}
# Generated by Doctor.Immunity

LOCATION: {discrepancy.get('lat', 0)}, {discrepancy.get('lon', 0)}
DEFICIT: {discrepancy['type']}
PAIN_INDEX: {discrepancy['pain']:.2f}

REMEDY:
1. Conduct a Minimal Test: Verify physical trace at this coordinate.
2. If match found, inject TRACE-Anchor.
3. If void remains, update Conducting Channel to bypass this node.

SIGMA_PRESCRIPTION_LOCKED
"""
        with open(filename, "w") as f:
            f.write(recipe_content)
        print(f"🩺 Prescription materialized: {filename}")

    def perform_scan(self):
        """Scans the grid for pain/conflicts and adds them as KML markers + prescriptions."""
        discrepancies = self.grid.check_coherence()
        for d in discrepancies:
            cell = self.grid.cells[d['cell']]
            # Convert grid local pos to mock lat/lon
            lat = 46.6 + (cell.pos[1] * 0.01)
            lon = 32.6 + (cell.pos[0] * 0.01)
            d['lat'], d['lon'] = lat, lon
            
            self.kml_gen.add_placemark(
                name=f"PAIN:{d['type']}",
                lat=lat,
                lon=lon,
                height=500,
                style="#pain_style",
                description=f"Status: {cell.state.value}\nPain: {cell.pain:.2f}\n{d['msg']}"
            )
            
            # Generate prescription if pain is high
            if cell.pain > 0.8:
                self.prescribe_remedy(d)

        print(f"🩺 Doctor Scan complete: {len(discrepancies)} pain markers identified.")
