import hashlib
import os
import time
from kml_generator import KMLGenerator
from gaia_grid import GaiaGrid, CellState

class Doctor:
    """System Immunity module: Translates discrepancies into KML Markers and SIGMA Prescriptions."""
    def __init__(self, grid: GaiaGrid, kml_gen: KMLGenerator):
        self.grid = grid
        self.kml_gen = kml_gen
        self.prescription_dir = "/Users/s0fractal/SIGMA/prescriptions"
        os.makedirs(self.prescription_dir, exist_ok=True)

    def diagnose_mismatch(self, discrepancy: dict):
        """Generates a prescription for an attribution mismatch (V72.1)."""
        m_id = f"MISMATCH_{int(time.time())}"
        filename = f"{self.prescription_dir}/RECIPE_{m_id}.sigma"
        
        claim_type = discrepancy.get('claim_type', 'literal')
        status = discrepancy.get('status', 'OPEN')
        
        # Symbolic claims are informational
        if claim_type == "symbolic" and discrepancy['severity'] < 0.4:
            print(f"🩺 Doctor: Symbolic claim detected. Downgrading to INFO.")
            return

        recipe_content = f"""# Σ-METABOLIC RECIPE: {m_id}
DOMAIN: Ethics.Spatial.V72.1
DEFICIT: ATTRIBUTION_MISMATCH
CLAIM_TYPE: {claim_type}
STATUS: {status}
SEVERITY: {discrepancy['severity']:.2f}

REMEDY:
1. Conduct a Minimal Test: Seek 3rd anchor or validate STRON_PAIR.
2. If Strong Pair found (Confidence > 0.9), transition to RESOLVED_BY_STRONG_PAIR.
3. If Symbolic, retain as MYTH and Dismiss Pain.

# Σ-PoI: {hashlib.sha256(m_id.encode()).hexdigest()[:16]}
SIGMA_PRESCRIPTION_LOCKED
"""
        with open(filename, "w") as f:
            f.write(recipe_content)
        print(f"🩺 Doctor: Refined Mismatch Prescription materialized -> {filename}")

    def prescribe_remedy(self, discrepancy: dict):
        """Generates a .sigma prescription for a discrepancy."""
        cell_id = discrepancy['cell']
        filename = f"{self.prescription_dir}/RECIPE_{cell_id}_{int(time.time())}.sigma"
        
        recipe_content = f"""# Σ-METABOLIC RECIPE: {cell_id}
# Generated by Doctor.Immunity

LOCATION: {discrepancy.get('lat', 0)}, {discrepancy.get('lon', 0)}
DEFICIT: {discrepancy['type']}
PAIN_INDEX: {discrepancy['pain']:.2f}

REMEDY:
1. Conduct a Minimal Test: Verify physical trace at this coordinate.
2. If match found, inject TRACE-Anchor.
3. If void remains, update Conducting Channel to bypass this node.

# Σ-PoI: {hashlib.sha256(recipe_content.encode()).hexdigest()[:16]}
SIGMA_PRESCRIPTION_LOCKED
"""
        with open(filename, "w") as f:
            f.write(recipe_content)
        print(f"🩺 Prescription materialized: {filename}")

    def perform_scan(self):
        """Scans the grid for pain/conflicts with Homeostasis (ignore pain < 0.2)."""
        discrepancies = self.grid.check_coherence()
        for d in discrepancies:
            cell = self.grid.cells[d['cell']]
            
            # Homeostasis: Ignore minimal noise
            if cell.pain < 0.2:
                print(f"🩺 Doctor: Ignoring minimal noise (Pain: {cell.pain:.2f})")
                continue

            # Convert grid local pos to mock lat/lon
            lat = 46.6 + (cell.pos[1] * 0.01)
            lon = 32.6 + (cell.pos[0] * 0.01)
            d['lat'], d['lon'] = lat, lon
            
            self.kml_gen.add_placemark(
                name=f"PAIN:{d['type']}",
                lat=lat,
                lon=lon,
                height=500,
                style="#pain_style",
                description=f"Status: {cell.state.value}\nPain: {cell.pain:.2f}\n{d['msg']}"
            )
            
            # Generate prescription if pain is high
            if cell.pain > 0.8:
                d['observable_signs'] = f"Conductance dropped below 0.5 with high pulse divergence."
                self.prescribe_remedy(d)

        print(f"🩺 Doctor Scan complete: {len(discrepancies)} pain markers identified.")
